name: hidro_pal
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.8.0
  firebase_auth: ^3.0.2
  cloud_firestore: 2.5.4
  google_fonts: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

